server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        #换成nginx的1111端口，做集群
        server-addr: 192.168.1.100:1111
      #        server-addr: localhost:8848  #配置nacos的地址

management:
  endpoints:
    web:
      exposure:
        include: '*'