server:
  port: 80


eureka:
  client:
    register-with-eureka: false #表示是否将自己注册进EurekaServer，默认是true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

#开启服务降级功能
feign:
  hystrix:
    enabled: true
